spring:
  application:
    name: dubbo-coupon-provider
  datasource:
    url: jdbc:mysql://124.223.90.7:3307/a_channel?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql123456

# Dubbo Protocol
dubbo:
  registry:
    id: zk-registry
    address: zookeeper://124.223.90.7:2181?timeout=600000
  protocol:
    name: dubbo
    port: 21900
  metadata-report:
    timeout: 10000
  config-center:
    timeout: 10000