publish:
  mqtt:
    #MQTT-服务端地址
    host: tcp://124.223.90.7:1883
    #MQTT-服务端用户名
    username: admin
    #MQTT-服务端密码
    password: 123456
    #MQTT-是否清理session
    cleansession: false
    #MQTT-当前客户端的唯一标识
    clientid: mqtt_publish
    #当前客户端的默认主题(大多数时候没什么用)
    default_topic: 测试
    #发送超时时间
    timeout: 1000
    #心跳时间
    keepalive: 10
    #连接超时时间
    connectionTimeout: 3000