spring:
  application:
    name: dubbo-member-provider
  datasource:
    url: ENC(S53QVo+WT212cUvVOrJ3K/5jiToUyr6DJ+1cUatNJkCDtNUAfk/Be4CsAaWruRWodvFwgeUMnfS666N4CSFDc6ME0ggGEW4/CM0E1ENRbBRJWIYO9A1fC52mSlMAemJeJc4qS+Kuq2Vv1d8U/G/hd6s7qn1vFx7DCXclmA1iK6S/m6cmJ6CYRphDcZY8IkyuuswfbGxcufJfX5hbXtNBEw==)
    username: ENC(gMRf3n52MuFKrgeSGVQgZW7Lo5OJkcIoBRH19Uvhvl4BmVpiQUEZmKACrqskVxiF)
    password: ENC(xNI/0r6KQBy7YC6T7YmcSvJ4zN89MSsZm1aO7wRTzCMlxyu09hH766MRKzPtCczs)

# Dubbo Protocol
dubbo:
  registry:
    id: zk-registry
    address: zookeeper://124.223.90.7:2181?timeout=6000
  protocol:
    name: dubbo
    port: 21800
  metadata-report:
    timeout: 10000
  config-center:
    timeout: 10000